// Generated by scripts/sync-team-branding.mjs. Do not edit by hand.
export const teamBranding = {
  "Anyone's Legend": {
    "code": "AL",
    "source": "lol-esports",
    "sourceName": "Anyone's Legend",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/anyone-s-legend.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1641199582689_.png"
  },
  "Bad Luck Gaming": {
    "code": "BLG",
    "source": "name-derived",
    "sourceName": "Bad Luck Gaming"
  },
  "Berlin International Gaming": {
    "code": "BIG",
    "source": "lol-esports",
    "sourceName": "Berlin International Gaming",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/berlin-international-gaming.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1674839453682_PRM_BIG-MonochromeLightBG.png"
  },
  "Bilibili Gaming": {
    "code": "BLG",
    "source": "lol-esports",
    "sourceName": "BILIBILI GAMING",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/bilibili-gaming.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1682322954525_Bilibili_Gaming_logo_20211.png"
  },
  "BNK FEARX": {
    "code": "BFX",
    "source": "lol-esports",
    "sourceName": "BNK FEARX",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/bnk-fearx.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1734691810721_BFXfullcolorfordarkbg.png"
  },
  "BoostGate Esports": {
    "code": "BGT",
    "source": "leaguepedia",
    "sourceName": "BoostGate Esports",
    "sourceUrl": "https://lol.fandom.com/wiki/BoostGate_Esports",
    "logo": "/team-logos/boostgate-esports.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/9/90/BoostGate_Esportslogo_square.png/revision/latest?cb=20250707005708"
  },
  "CBK -MA": {
    "code": "CBK",
    "source": "name-derived",
    "sourceName": "CBK -MA"
  },
  "Chiefs Esports Club": {
    "code": "CHF",
    "source": "leaguepedia",
    "sourceName": "Chiefs Esports Club",
    "sourceUrl": "https://lol.fandom.com/wiki/Chiefs_Esports_Club",
    "logo": "/team-logos/chiefs-esports-club.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/f/f7/Chiefs_Esports_Clublogo_square.png/revision/latest?cb=20250223132237"
  },
  "CHIME (Oceanic Team)": {
    "code": "CHIME",
    "source": "name-derived",
    "sourceName": "CHIME (Oceanic Team)"
  },
  "Cloud9": {
    "code": "C9",
    "source": "lol-esports",
    "sourceName": "Cloud9 Kia",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/cloud9.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1736924120254_C9Kia_IconBlue_Transparent_2000x2000.png"
  },
  "clownoce69's party": {
    "code": "CP",
    "source": "name-derived",
    "sourceName": "clownoce69's party"
  },
  "Cruise dudes": {
    "code": "CD",
    "source": "name-derived",
    "sourceName": "Cruise dudes"
  },
  "CTBC Flying Oyster": {
    "code": "CFO",
    "source": "lol-esports",
    "sourceName": "CTBC Flying Oyster",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/ctbc-flying-oyster.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1656307849320_CFO_Logo.png"
  },
  "Deep Cross Gaming": {
    "code": "DCG",
    "source": "lol-esports",
    "sourceName": "Relove Deep Cross Gaming",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/deep-cross-gaming.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1773832146741_LCP_DCG_Full_W.png"
  },
  "DetonatioN FocusMe": {
    "code": "DFM",
    "source": "lol-esports",
    "sourceName": "DetonatioN FocusMe",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/detonation-focusme.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1673415140442_dfm.png"
  },
  "Dignitas": {
    "code": "DIG",
    "source": "lol-esports",
    "sourceName": "Dignitas",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/dignitas.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/DIG-FullonDark.png"
  },
  "Disguised": {
    "code": "DSG",
    "source": "lol-esports",
    "sourceName": "Disguised",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/disguised.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1731496922454_Disguised-Wordmark-Yellow-Main.png"
  },
  "DN SOOPers": {
    "code": "DNS",
    "source": "lol-esports",
    "sourceName": "DN SOOPers",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/dn-soopers.webp",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1767340467921_DN_SOOPerslogo_profile.webp"
  },
  "Dplus KIA": {
    "code": "DK",
    "source": "lol-esports",
    "sourceName": "Dplus KIA",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/dplus-kia.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1673260049703_DPlusKIALOGO11.png"
  },
  "EDward Gaming": {
    "code": "EDG",
    "source": "lol-esports",
    "sourceName": "EDWARD GAMING",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/edward-gaming.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1631819297476_edg-2021-worlds.png"
  },
  "Faerie Charm (Singaporean Team)": {
    "code": "FRC",
    "source": "leaguepedia",
    "sourceName": "Faerie Charm",
    "sourceUrl": "https://lol.fandom.com/wiki/Faerie_Charm_(Singaporean_Team)",
    "logo": "/team-logos/faerie-charm-singaporean-team.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/1/1a/Faerie_Charm_%28Singaporean_Team%29logo_square.png/revision/latest?cb=20250827141056"
  },
  "Fluxo W7M": {
    "code": "FX",
    "source": "lol-esports",
    "sourceName": "Fluxo W7M",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/fluxo-w7m.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1766161431111_LogoColorida.png"
  },
  "FlyQuest": {
    "code": "FLY",
    "source": "lol-esports",
    "sourceName": "FlyQuest",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/flyquest.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/flyquest-new-on-dark.png"
  },
  "Fnatic": {
    "code": "FNC",
    "source": "leaguepedia",
    "sourceName": "Fnatic",
    "sourceUrl": "https://lol.fandom.com/wiki/Fnatic",
    "logo": "/team-logos/fnatic.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/6/61/Fnaticlogo_profile.png/revision/latest?cb=20260112184526"
  },
  "Fukuoka SoftBank HAWKS gaming": {
    "code": "SHG",
    "source": "lol-esports",
    "sourceName": "Fukuoka SoftBank HAWKS gaming",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/fukuoka-softbank-hawks-gaming.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1725885083108_SHG_White_Main.png"
  },
  "Full Sense": {
    "code": "FS",
    "source": "leaguepedia",
    "sourceName": "Full Sense",
    "sourceUrl": "https://lol.fandom.com/wiki/Full_Sense",
    "logo": "/team-logos/full-sense.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/e/e2/Full_Senselogo_profile.png/revision/latest?cb=20260203102319"
  },
  "FunPlus Phoenix": {
    "code": "FPX",
    "source": "leaguepedia",
    "sourceName": "FunPlus Phoenix",
    "sourceUrl": "https://lol.fandom.com/wiki/FunPlus_Phoenix"
  },
  "FURIA": {
    "code": "FUR",
    "source": "lol-esports",
    "sourceName": "FURIA",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/furia.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/FURIA---black.png"
  },
  "G2 Esports": {
    "code": "G2",
    "source": "lol-esports",
    "sourceName": "G2 Esports",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/g2-esports.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/G2-FullonDark.png"
  },
  "GAM Esports": {
    "code": "GAM",
    "source": "lol-esports",
    "sourceName": "GAM Esports",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/gam-esports.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1643263093448_GAMyellow.png"
  },
  "Geekay Esports": {
    "code": "GK",
    "source": "leaguepedia",
    "sourceName": "Geekay Esports",
    "sourceUrl": "https://lol.fandom.com/wiki/Geekay_Esports",
    "logo": "/team-logos/geekay-esports.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/f/f6/Geekay_Esportslogo_square.png/revision/latest?cb=20231116145944"
  },
  "Gen.G": {
    "code": "GEN",
    "source": "lol-esports",
    "sourceName": "Gen.G Esports",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/gen-g.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1773829250929_GENGLOGO_GOLD.png"
  },
  "GiantX": {
    "code": "GX",
    "source": "lol-esports",
    "sourceName": "GIANTX",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/giantx.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1765897105091_GIANTX-logotype-white.png"
  },
  "Ground Zero Gaming": {
    "code": "GZ",
    "source": "lol-esports",
    "sourceName": "Ground Zero Gaming",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/ground-zero-gaming.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1766395585595_LCP_TEAMLogo_GZ_Full_B.png"
  },
  "HANJIN BRION": {
    "code": "BRO",
    "source": "lol-esports",
    "sourceName": "HANJIN BRION",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/hanjin-brion.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1716454325887_Nowyprojekt.png"
  },
  "Hanwha Life Esports": {
    "code": "HLE",
    "source": "lol-esports",
    "sourceName": "Hanwha Life Esports",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/hanwha-life-esports.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1631819564399_hle-2021-worlds.png"
  },
  "High Tempo Gaming": {
    "code": "HTE",
    "source": "leaguepedia",
    "sourceName": "High Tempo Esports",
    "sourceUrl": "https://lol.fandom.com/wiki/High_Tempo_Esports",
    "logo": "/team-logos/high-tempo-gaming.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/d/d9/High_Tempo_Esportslogo_square.png/revision/latest?cb=20220812183237"
  },
  "Inferno Esports": {
    "code": "inF",
    "source": "leaguepedia",
    "sourceName": "inFerno eSports",
    "sourceUrl": "https://lol.fandom.com/wiki/InFerno_eSports"
  },
  "Inferno Esports (Filipino Team)": {
    "code": "IE",
    "source": "leaguepedia",
    "sourceName": "Inferno Esports",
    "sourceUrl": "https://lol.fandom.com/wiki/Inferno_Esports_(Filipino_Team)",
    "logo": "/team-logos/inferno-esports-filipino-team.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/b/b2/Inferno_Esports_%28Filipino_Team%29logo_square.png/revision/latest?cb=20250710061519"
  },
  "Invictus Gaming": {
    "code": "IG",
    "source": "lol-esports",
    "sourceName": "Invictus Gaming",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/invictus-gaming.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1634762917340_300px-Invictus_Gaming_logo.png"
  },
  "JD Gaming": {
    "code": "JDG",
    "source": "lol-esports",
    "sourceName": "Beijing JDG Esports",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/jd-gaming.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1627457924722_29.png"
  },
  "Karmine Corp": {
    "code": "KC",
    "source": "lol-esports",
    "sourceName": "Karmine Corp",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/karmine-corp.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1704714951336_KC.png"
  },
  "Karmine Corp Blue": {
    "code": "KCB",
    "source": "lol-esports",
    "sourceName": "Karmine Corp Blue",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/karmine-corp-blue.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1765897112519_WHITE.png"
  },
  "Kiwoom DRX": {
    "code": "KRX",
    "source": "lol-esports",
    "sourceName": "KIWOOM DRX",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/kiwoom-drx.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1774247803537_horizontal_EN_Wh.png"
  },
  "KT Korean Team": {
    "code": "KKT",
    "source": "name-derived",
    "sourceName": "KT Korean Team"
  },
  "KT Rolster": {
    "code": "KT",
    "source": "lol-esports",
    "sourceName": "kt Rolster",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/kt-rolster.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/kt_darkbackground.png"
  },
  "Leviatan": {
    "code": "LEV",
    "source": "lol-esports",
    "sourceName": "LEVIATÁN",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/leviatan.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1643795049372_LEV-CLAROWhite.png"
  },
  "LGD Gaming": {
    "code": "LGD",
    "source": "lol-esports",
    "sourceName": "LGD GAMING",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/lgd-gaming.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/LGD-FullonDark-1.png"
  },
  "Little Mermae": {
    "code": "LM",
    "source": "name-derived",
    "sourceName": "Little Mermae"
  },
  "LNG Esports": {
    "code": "LNG",
    "source": "lol-esports",
    "sourceName": "Suzhou LNG Esports",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/lng-esports.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1717487697003_LNGlogo.png"
  },
  "LØS": {
    "code": "LOS",
    "source": "lol-esports",
    "sourceName": "LOS",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/l-s.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1784013312149_LOS-OLaranja.png"
  },
  "Los Ratones": {
    "code": "LR",
    "source": "leaguepedia",
    "sourceName": "Los Ratones",
    "sourceUrl": "https://lol.fandom.com/wiki/Los_Ratones",
    "logo": "/team-logos/los-ratones.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/f/fd/Los_Ratoneslogo_square.png/revision/latest?cb=20251224022057"
  },
  "LOUD": {
    "code": "LOUD",
    "source": "lol-esports",
    "sourceName": "LOUD",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/loud.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/Logo-LOUD-Esports_Original.png"
  },
  "LYON": {
    "code": "LYON",
    "source": "lol-esports",
    "sourceName": "LYON",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/lyon.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1743717443673_isotypelyon-03.png"
  },
  "MCOM eSports": {
    "code": "MCOM",
    "source": "name-derived",
    "sourceName": "MCOM eSports"
  },
  "MGN Vikings Esports": {
    "code": "MVKE",
    "source": "leaguepedia",
    "sourceName": "MGN Vikings Esports",
    "sourceUrl": "https://lol.fandom.com/wiki/MGN_Vikings_Esports",
    "logo": "/team-logos/mgn-vikings-esports.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/8/84/Vikings_Esports_%282023_Vietnamese_Team%29logo_profile.png/revision/latest?cb=20240108193644"
  },
  "Movistar KOI": {
    "code": "MKOI",
    "source": "lol-esports",
    "sourceName": "Movistar KOI",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/movistar-koi.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1734012609283_MKOI_FullColor_Blue.png"
  },
  "MVK Esports": {
    "code": "MVK",
    "source": "lol-esports",
    "sourceName": "MVK Esports",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/mvk-esports.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1767089709161_White_Logo.png"
  },
  "Natus Vincere": {
    "code": "NAVI",
    "source": "lol-esports",
    "sourceName": "Natus Vincere",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/natus-vincere.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1752746833620_NAVI_FullColor.png"
  },
  "Ninjas in Pyjamas": {
    "code": "NIP",
    "source": "lol-esports",
    "sourceName": "Shenzhen NINJAS IN PYJAMAS",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/ninjas-in-pyjamas.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1673425724696_NIP-Symbol-RGB-NeonYellow1.png"
  },
  "Nongshim RedForce": {
    "code": "NS",
    "source": "lol-esports",
    "sourceName": "NONGSHIM RED FORCE",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/nongshim-redforce.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/NSFullonDark.png"
  },
  "Oh My God": {
    "code": "OMG",
    "source": "leaguepedia",
    "sourceName": "Oh My God",
    "sourceUrl": "https://lol.fandom.com/wiki/Oh_My_God",
    "logo": "/team-logos/oh-my-god.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/0/0d/Oh_My_Godlogo_square.png/revision/latest?cb=20260109133750"
  },
  "paiN Gaming": {
    "code": "PAIN",
    "source": "lol-esports",
    "sourceName": "paiN Gaming",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/pain-gaming.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1674657011011_pain_logo_white.png"
  },
  "Polarchair": {
    "code": "POLA",
    "source": "name-derived",
    "sourceName": "Polarchair"
  },
  "PSG Talon": {
    "code": "PSG",
    "source": "leaguepedia",
    "sourceName": "PSG Talon",
    "sourceUrl": "https://lol.fandom.com/wiki/PSG_Talon",
    "logo": "/team-logos/psg-talon.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/3/34/PSG_Talonlogo_profile.png/revision/latest?cb=20250715143201"
  },
  "QT DIG∞": {
    "code": "QTD",
    "source": "leaguepedia",
    "sourceName": "QT DIG∞",
    "sourceUrl": "https://lol.fandom.com/wiki/QT_DIG",
    "logo": "/team-logos/qt-dig.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/6/6b/QT_DIGlogo_profile.png/revision/latest?cb=20250409144853"
  },
  "RED Canids": {
    "code": "RED",
    "source": "lol-esports",
    "sourceName": "RED Kalunga",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/red-canids.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1631820575924_red-2021-worlds.png"
  },
  "Rich Dynasty": {
    "code": "RD",
    "source": "name-derived",
    "sourceName": "Rich Dynasty"
  },
  "Rogue": {
    "code": "RGE",
    "source": "leaguepedia",
    "sourceName": "Rogue",
    "sourceUrl": "https://lol.fandom.com/wiki/Rogue_(European_Team)",
    "logo": "/team-logos/rogue.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/a/a4/Rogue_%28European_Team%29logo_square.png/revision/latest?cb=20231125191715"
  },
  "Royal Never Give Up": {
    "code": "RNG",
    "source": "leaguepedia",
    "sourceName": "Royal Never Give Up",
    "sourceUrl": "https://lol.fandom.com/wiki/Royal_Never_Give_Up",
    "logo": "/team-logos/royal-never-give-up.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/1/1a/Royal_Never_Give_Uplogo_profile.png/revision/latest?cb=20260204112058"
  },
  "S8UL Esports": {
    "code": "S8UL",
    "source": "leaguepedia",
    "sourceName": "S8UL Esports",
    "sourceUrl": "https://lol.fandom.com/wiki/S8UL_Esports",
    "logo": "/team-logos/s8ul-esports.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/d/d8/S8UL_Esportslogo_square.png/revision/latest?cb=20260521084617"
  },
  "Saigon Dino": {
    "code": "DINO",
    "source": "lol-esports",
    "sourceName": "Saigon Dino",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/saigon-dino.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1737108816278_SaigonDino-DINOLogo2025.png"
  },
  "Saving OCE": {
    "code": "SVO",
    "source": "leaguepedia",
    "sourceName": "Saving OCE",
    "sourceUrl": "https://lol.fandom.com/wiki/Saving_OCE",
    "logo": "/team-logos/saving-oce.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/c/cd/Saving_OCElogo_square.png/revision/latest?cb=20250917073518"
  },
  "Senshi eSports (Benelux Team)": {
    "code": "SNSH",
    "source": "leaguepedia",
    "sourceName": "Senshi eSports",
    "sourceUrl": "https://lol.fandom.com/wiki/Senshi_eSports_(Benelux_Team)",
    "logo": "/team-logos/senshi-esports-benelux-team.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/1/1d/Senshi_eSports_%28Benelux_Team%29logo_square.png/revision/latest?cb=20230821114141"
  },
  "Sentinels": {
    "code": "SEN",
    "source": "lol-esports",
    "sourceName": "Sentinels",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/sentinels.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1767769784669_Sentinels_2020_Icon.png"
  },
  "Shifters": {
    "code": "SHFT",
    "source": "leaguepedia",
    "sourceName": "Shifters",
    "sourceUrl": "https://lol.fandom.com/wiki/Shifters",
    "logo": "/team-logos/shifters.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/2/2a/Shifterslogo_profile.png/revision/latest?cb=20260114130755"
  },
  "Shopify Rebellion": {
    "code": "SR",
    "source": "lol-esports",
    "sourceName": "Shopify Rebellion",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/shopify-rebellion.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1701424227458_Teams204_Shopify_1632869404072.png"
  },
  "SK Gaming": {
    "code": "SK",
    "source": "leaguepedia",
    "sourceName": "SK Gaming",
    "sourceUrl": "https://lol.fandom.com/wiki/SK_Gaming",
    "logo": "/team-logos/sk-gaming.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/2/2f/SK_Gaminglogo_profile.png/revision/latest?cb=20221120001426"
  },
  "T1": {
    "code": "T1",
    "source": "lol-esports",
    "sourceName": "T1",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/t1.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1726801573959_539px-T1_2019_full_allmode.png"
  },
  "TALON (Hong Kong Team)": {
    "code": "TLN",
    "source": "name-derived",
    "sourceName": "TALON (Hong Kong Team)"
  },
  "Team BDS": {
    "code": "BDS",
    "source": "leaguepedia",
    "sourceName": "Team BDS",
    "sourceUrl": "https://lol.fandom.com/wiki/Team_BDS",
    "logo": "/team-logos/team-bds.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/0/06/Team_BDSlogo_profile.png/revision/latest?cb=20220111204832"
  },
  "Team Heretics": {
    "code": "TH",
    "source": "leaguepedia",
    "sourceName": "Team Heretics",
    "sourceUrl": "https://lol.fandom.com/wiki/Team_Heretics",
    "logo": "/team-logos/team-heretics.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/b/bf/Team_Hereticslogo_square.png/revision/latest?cb=20251230025102"
  },
  "Team in Progress": {
    "code": "TIP",
    "source": "name-derived",
    "sourceName": "Team in Progress"
  },
  "Team Liquid": {
    "code": "TLAW",
    "source": "lol-esports",
    "sourceName": "Team Liquid Alienware",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/team-liquid.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1769357207762_TLAlienware_Minimal_Bug-White.png"
  },
  "Team Secret": {
    "code": "TS",
    "source": "lol-esports",
    "sourceName": "Team Secret",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/team-secret.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1656693717651_TS.png"
  },
  "Team Secret Whales": {
    "code": "TSW",
    "source": "lol-esports",
    "sourceName": "Team Secret Whales",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/team-secret-whales.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1774598000328_White_EyeText_600p.png"
  },
  "Team Vitality": {
    "code": "VIT",
    "source": "lol-esports",
    "sourceName": "Team Vitality",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/team-vitality.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1675865863968_Vitality_FullColor.png"
  },
  "Team WE": {
    "code": "WE",
    "source": "lol-esports",
    "sourceName": "Xi'an Team WE",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/team-we.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1634763008788_220px-Team_WE_logo.png"
  },
  "Team.Void": {
    "code": "VOID",
    "source": "name-derived",
    "sourceName": "Team.Void"
  },
  "The Outcasts": {
    "code": "TO",
    "source": "name-derived",
    "sourceName": "The Outcasts"
  },
  "ThunderTalk Gaming": {
    "code": "TT",
    "source": "lol-esports",
    "sourceName": "THUNDER TALK GAMING",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/thundertalk-gaming.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/TT-FullonDark.png"
  },
  "TMCFYN": {
    "code": "TMCF",
    "source": "name-derived",
    "sourceName": "TMCFYN"
  },
  "Top Esports": {
    "code": "TES",
    "source": "lol-esports",
    "sourceName": "TOP ESPORTS",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/top-esports.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1592592064571_TopEsportsTES-01-FullonDark.png"
  },
  "Twisted Takeover": {
    "code": "TT",
    "source": "name-derived",
    "sourceName": "Twisted Takeover"
  },
  "Ultra Prime": {
    "code": "UP",
    "source": "leaguepedia",
    "sourceName": "Ultra Prime",
    "sourceUrl": "https://lol.fandom.com/wiki/Ultra_Prime",
    "logo": "/team-logos/ultra-prime.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/e/e8/Ultra_Primelogo_profile.png/revision/latest?cb=20260109073324"
  },
  "UNSW Howl": {
    "code": "UNSW",
    "source": "name-derived",
    "sourceName": "UNSW Howl"
  },
  "UQ Eagles": {
    "code": "UQ",
    "source": "name-derived",
    "sourceName": "UQ Eagles"
  },
  "Vespertine": {
    "code": "VESP",
    "source": "name-derived",
    "sourceName": "Vespertine"
  },
  "Vivo Keyd Stars": {
    "code": "VKS",
    "source": "lol-esports",
    "sourceName": "Vivo Keyd Stars",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/vivo-keyd-stars.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1670542079678_vks.png"
  },
  "Weibo Gaming": {
    "code": "WBG",
    "source": "lol-esports",
    "sourceName": "WeiboGaming",
    "sourceUrl": "https://lolesports.com",
    "logo": "/team-logos/weibo-gaming.png",
    "remoteLogoUrl": "https://static.lolesports.com/teams/1641202879910_3.png"
  },
  "Yang Dae Pal Korean BBQ Restaurant": {
    "code": "YDP",
    "source": "leaguepedia",
    "sourceName": "Yang Dae Pal",
    "sourceUrl": "https://lol.fandom.com/wiki/Yang_Dae_Pal_Korean_BBQ_Restaurant",
    "logo": "/team-logos/yang-dae-pal-korean-bbq-restaurant.webp",
    "remoteLogoUrl": "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/b/bc/Yang_Dae_Pal_Korean_BBQ_Restaurantlogo_profile.png/revision/latest?cb=20250819221535"
  },
  "Yee Club": {
    "code": "YC",
    "source": "name-derived",
    "sourceName": "Yee Club"
  }
} as const
